sudoo: required
services:
  - docker

before_install:
  - docker build -t bunorita/docker-prod-workflow -f Dockerfile.dev .

script:
  - docker run -e CI=true bunorita/docker-prod-workflow yarn test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: ap-northeast-1
  app: docker-react
  env: DockerReact-env
  bucket_name: elasticbeanstalk-ap-northeast-1-828490920656
  bucket_path: docker-react
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
