sudoo: required
services:
  - docker

before_install:
  - docker build -t bunorita/docker-prod-workflow -f Dockerfile.dev .

script:
  - docker run -e CI=true bunorita/docker-prod-workflow yarn test -- --coverage